# CLIENTS

In [36]:
import pandas as pd

In [40]:
clients = pd.read_csv('Data/CLIENTS.csv', delimiter=';')
clients.head()
len(clients)

3125800

In [38]:
clients['GENDER'].value_counts()

Mme              2714740
M                 286650
Mle               119070
Ste                 2142
MME                 1846
Non Renseigne        805
SOC                  545
ARU                    1
M.                     1
Name: GENDER, dtype: int64

We want to count the number of men and women:

In [43]:
clients['GENDER'] = clients['GENDER'].replace(['MME', 'Mle', 'Mme'], 'F')
clients['GENDER'] = clients['GENDER'].replace(['M.'], 'M')
clients['GENDER'] = clients['GENDER'].replace(['Ste', 'SOC', 'Non Renseigne', 'ARU'], 'Other')

In [44]:
nb_women = len(clients[clients['GENDER'] == 'F'])
nb_men = len(clients[clients['GENDER'] == 'M'])
nb_other = len(clients[clients['GENDER'] == 'Other'])
print(nb_women)
print(nb_men)
print(nb_other)

2835656
286651
3493

In [45]:
nb_women + nb_men + nb_other

3125800

In the record we have, the company has 3 125 800 customers, of which 2 835 656 are women.

# CMD

In [58]:
cmd = pd.read_csv('Data/CMD.csv', delimiter=';')
cmd.head()

,Unnamed: 0,CLIENT_NUMBER,ORDER_NUMBER,ORDER_DATE,ORDER_CHANNEL,PRE_TAX_AMOUNT,CVIC
0,0,7178742953965764755,2302390,2010-01-05,Telephone,84.28,True
1,1,-2373390172893352743,2302392,2010-01-17,Telephone,97.85,True
2,2,-240944575938990062,2302393,2010-01-05,Telephone,58.45,True
3,3,1720395480962300217,2302394,2010-01-05,Telephone,31.19,True
4,4,7161131950067982732,2302396,2010-01-14,Telephone,37.45,True

In [60]:
cmd['ORDER_CHANNEL'].value_counts()

Courier          3543250
Internet         1648148
Telephone        1400281
Magasin           727577
Non Renseigne       3971
Name: ORDER_CHANNEL, dtype: int64

In [71]:
cmd_internet = cmd[cmd['ORDER_CHANNEL']=='Internet']
cmd_internet.head()

,Unnamed: 0,CLIENT_NUMBER,ORDER_NUMBER,ORDER_DATE,ORDER_CHANNEL,PRE_TAX_AMOUNT,CVIC
633861,633861,-1042312883270123787,3005216,2015-12-28,Internet,249.10,False
634168,634168,-2328994922030438275,3005576,2016-01-05,Internet,308.92,False
634413,634413,-3470671720898992802,3005855,2016-01-08,Internet,250.51,False
635627,635627,7424562347642472977,3007195,2016-03-01,Internet,252.22,False
636492,636492,1493995330919931635,3008190,2016-02-03,Internet,94.47,False

In [68]:
# total number of orders of 
nb_order = len(cmd)
nb_order

7323227

In [72]:
nb_order_mag = len(cmd[cmd['ORDER_CHANNEL'] == 'Courier']) + len(cmd[cmd['ORDER_CHANNEL'] == 'Telephone'])
nb_order_internet = len(cmd_internet)
print(nb_order_mag)
print(nb_order_internet)
print(nb_order_mag/nb_order)
print(nb_order_internet/nb_order)

4943531
1648148
0.6750481720694989
0.22505761462808677

In [74]:
online_orders = pd.DataFrame(cmd_internet.groupby('ORDER_DATE').CLIENT_NUMBER.nunique())
online_orders = online_orders.reset_index()
online_orders.head()

   ORDER_DATE  CLIENT_NUMBER
0  2010-01-05            443
1  2010-01-06            646
2  2010-01-07            440
3  2010-01-10            428
4  2010-01-11            799

In [76]:
pd.to_datetime(online_orders['ORDER_DATE'])
online_orders.head()

   ORDER_DATE  CLIENT_NUMBER
0  2010-01-05            443
1  2010-01-06            646
2  2010-01-07            440
3  2010-01-10            428
4  2010-01-11            799

In [78]:
# Considering only the period from 2017-08-08 to 2018-03-31

adjusted_nb_of_orders = online_orders.loc[(online_orders['ORDER_DATE'] >= '2017-08-08') & (online_orders['ORDER_DATE'] <= '2018-03-31')]
adjusted_nb_of_orders.head()

      ORDER_DATE  CLIENT_NUMBER
2198  2017-08-08            720
2199  2017-08-09            378
2200  2017-08-10            430
2201  2017-08-11            495
2202  2017-08-12            292

In [79]:
total_nb_purchase = adjusted_nb_of_orders['CLIENT_NUMBER'].sum()
total_nb_purchase

187968

## The total number of purchase from 08-08-2017 to 31-03-2018 is 718 077.

# LOGS

In [4]:
# We merge all log files, from 08-08-2017 to 31-03-2018

import glob 
log_path = glob.glob('Data/LOG*.csv')
logs = pd.DataFrame()
log_list = []
for log_file in log_path:
   df = pd.read_csv(log_file, index_col=None, delimiter=';')
   log_list.append(df)
logs = pd.concat(log_list)

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [86]:
logs_table = logs

In [87]:
logs_table.loc[:, 'SESSION_DATE'] = pd.to_datetime(logs_table['SESSION_START_DATE']).dt.date
logs_table

,CONNECTED_SESSION,DEVICE_MODEL,DEVICE_TYPE,EVENT_DATE,GLOBAL_SOURCES,ID_SESSION,LOADINGS,PAGES,SESSION_START_DATE,Unnamed: 0,Unnamed: 0.1,VISITOR_ID,SESSION_DATE
0,OUI,NaN,Smartphone,2017-08-08 00:02:06,Liens Sponsorisés,1,1,accueil,2017-08-08 00:02:06,0,NaN,381225,2017-08-08
1,OUI,NaN,Ordinateur,2017-08-08 00:03:27,Accès Direct,13,1,accueil,2017-08-08 00:01:32,1,NaN,563053,2017-08-08
2,OUI,NaN,Ordinateur,2017-08-08 00:22:04,Accès Direct,13,1,accueil,2017-08-08 00:01:32,2,NaN,563053,2017-08-08
3,OUI,NaN,Ordinateur,2017-08-08 00:01:32,Accès Direct,23,1,accueil,2017-08-08 00:01:29,3,NaN,706588,2017-08-08
4,NON,NaN,Ordinateur,2017-08-08 00:14:08,Accès Direct,27,1,accueil,2017-08-08 00:01:30,4,NaN,0,2017-08-08
5,NON,iPad,Tablette,2017-08-08 00:03:09,Accès Direct,29,1,accueil,2017-08-08 00:01:31,5,NaN,0,2017-08-08
6,NON,iPhone,Smartphone,2017-08-08 00:06:02,Accès Direct,30,1,accueil,2017-08-08 00:01:31,6,NaN,0,2017-08-08
7,NON,NaN,Ordinateur,2017-08-08 00:01:54,Affiliation et partenaires,33,1,accueil,2017-08-08 00:01:54,7,NaN,0,2017-08-08
8,NON,sm-g935f,Smartphone,2017-08-08 00:08:15,Accès Direct,34,1,accueil,2017-08-08 00:01:32,8,NaN,0,2017-08-08
9,NON,iPhone,Smartphone,2017-08-08 00:01:32,Moteurs,35,1,accueil,2017-08-08 00:01:32,9,NaN,0,2017-08-08
10,NON,NaN,Ordinateur,2017-08-08 00:01:36,Accès Direct,41,1,accueil,2017-08-08 00:01:36,10,NaN,0,2017-08-08
11,NON,NaN,Ordinateur,2017-08-08 00:02:02,Affiliation et partenaires,45,1,accueil,2017-08-08 00:02:02,11,NaN,0,2017-08-08
12,NON,NaN,Ordinateur,2017-08-08 00:02:22,Email marketing,48,1,accueil,2017-08-08 00:02:22,12,NaN,0,2017-08-08
13,NON,NaN,Ordinateur,2017-08-08 00:14:23,Email marketing,48,1,accueil,2017-08-08 00:02:22,13,NaN,0,2017-08-08
14,NON,NaN,Ordinateur,2017-08-08 00:02:55,Affiliation et partenaires,56,1,accueil,2017-08-08 00:02:55,14,NaN,0,2017-08-08
15,NON,VNS-L31,Smartphone,2017-08-08 00:02:57,Moteurs,57,1,accueil,2017-08-08 00:02:57,15,NaN,0,2017-08-08
16,NON,NaN,Ordinateur,2017-08-08 00:03:07,Affiliation et partenaires,59,1,accueil,2017-08-08 00:03:07,16,NaN,0,2017-08-08
17,OUI,101 Oxygen,Tablette,2017-08-08 00:03:19,Moteurs,64,1,accueil,2017-08-08 00:03:19,17,NaN,572702,2017-08-08
18,OUI,101 Oxygen,Tablette,2017-08-08 00:09:42,Moteurs,64,1,accueil,2017-08-08 00:03:19,18,NaN,572702,2017-08-08
19,OUI,101 Oxygen,Tablette,2017-08-08 00:10:36,Moteurs,64,1,accueil,2017-08-08 00:03:19,19,NaN,572702,2017-08-08
20,NON,NaN,Ordinateur,2017-08-08 00:04:52,Affiliation et partenaires,80,1,accueil,2017-08-08 00:04:52,20,NaN,0,2017-08-08
21,NON,sm-g920f,Smartphone,2017-08-08 00:06:30,Moteurs,83,1,accueil,2017-08-08 00:05:10,21,NaN,0,2017-08-08
22,NON,SM-G357FZ,Smartphone,2017-08-08 00:05:11,Moteurs,84,1,accueil,2017-08-08 00:05:11,22,NaN,0,2017-08-08
23,NON,NaN,Ordinateur,2017-08-08 00:05:50,Liens Sponsorisés,91,1,accueil,2017-08-08 00:05:50,23,NaN,0,2017-08-08
24,NON,iPad,Tablette,2017-08-08 00:05:58,Moteurs,94,1,accueil,2017-08-08 00:05:58,24,NaN,0,2017-08-08
25,NON,NaN,Ordinateur,2017-08-08 00:05:59,Liens Sponsorisés,96,1,accueil,2017-08-08 00:05:59,25,NaN,0,2017-08-08
26,NON,f3311,Smartphone,2017-08-08 00:06:31,Accès Direct,106,1,accueil,2017-08-08 00:06:31,26,NaN,0,2017-08-08
27,NON,NaN,Ordinateur,2017-08-08 00:06:55,Accès Direct,110,1,accueil,2017-08-08 00:06:55,27,NaN,0,2017-08-08
28,NON,NaN,Ordinateur,2017-08-08 00:07:01,Moteurs,112,1,accueil,2017-08-08 00:07:01,28,NaN,0,2017-08-08
29,NON,NaN,Ordinateur,2017-08-08 00:07:10,Liens Sponsorisés,114,1,accueil,2017-08-08 00:07:10,29,NaN,0,2017-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2739689,NON,NaN,Ordinateur,2018-03-31 21:22:37,Email marketing,50177,1,les-nouveautes-du-printemps,2018-03-31 21:17:02,2739689,NaN,0,2018-03-31
2739690,NON,iPad,Tablette,2018-03-31 21:23:53,Email marketing,50229,1,les-nouveautes-du-printemps,2018-03-31 21:19:07,2739690,NaN,0,2018-03-31
2739691,NON,NaN,Ordinateur,2018-03-31 21:19:17,Accès Direct,50231,1,les-nouveautes-du-printemps,2018-03-31 21:19:09,2739691,NaN,0,2018-03-31
2739692,NON,NaN,Ordinateur,2018-03-31 22:23:54,Liens Sponsorisés,50273,1,les-nouveautes-du-printemps,2018-03-31 21:21:05,2739692,NaN,0,2018-03-31
2739693,NON,iPad,Tablette,2018-03-31 21:55:16,Liens Sponsorisés,50308,1,les-nouveautes-du-printemps,2018-03-31 21:22:13,2739693,NaN,0,2018-03-31
2739694,OUI,NaN,Ordinateur,2018-03-31 21:33:39,Liens Sponsorisés,50368,1,les-nouveautes-du-printemps,2018-03-31 21:24:57,2739694,NaN,331542,2018-03-31
2739695,OUI,NaN,Ordinateur,2018-03-31 21:35:09,Liens Sponsorisés,50368,1,les-nouveautes-du-printemps,2018-03-31 21:24:57,2739695,NaN,331542,2018-03-31
2739696,OUI,NaN,Ordinateur,2018-03-31 21:40:55,Liens Sponsorisés,50368,1,les-nouveautes-du-printemps,2018-03-31 21:24:57,2739696,NaN,331542,2018-03-31
2739697,NON,NaN,Ordinateur,2018-03-31 21:28:07,Email marketing,50434,1,les-nouveautes-du-printemps,2018-03-31 21:27:34,2739697,NaN,0,2018-03-31
2739698,NON,sm-t820,Tablette,2018-03-31 21:33:01,Liens Sponsorisés,50498,1,les-nouveautes-du-printemps,2018-03-31 21:30:01,2739698,NaN,0,2018-03-31
2739699,NON,sm-t820,Tablette,2018-03-31 21:33:07,Liens Sponsorisés,50498,1,les-nouveautes-du-printemps,2018-03-31 21:30:01,2739699,NaN,0,2018-03-31
2739700,NON,sm-t820,Tablette,2018-03-31 21:33:15,Liens Sponsorisés,50498,1,les-nouveautes-du-printemps,2018-03-31 21:30:01,2739700,NaN,0,2018-03-31
2739701,NON,iPad,Tablette,2018-03-31 21:30:35,Accès Direct,50501,1,les-nouveautes-du-printemps,2018-03-31 21:30:05,2739701,NaN,0,2018-03-31
2739702,NON,NaN,Tablette,2018-03-31 21:33:28,Moteurs,50526,1,les-nouveautes-du-printemps,2018-03-31 21:31:09,2739702,NaN,0,2018-03-31
2739703,NON,sm-t550,Tablette,2018-03-31 21:39:23,Liens Sponsorisés,50634,1,les-nouveautes-du-printemps,2018-03-31 21:36:04,2739703,NaN,0,2018-03-31
2739704,NON,sm-t550,Tablette,2018-03-31 21:44:36,Liens Sponsorisés,50634,1,les-nouveautes-du-printemps,2018-03-31 21:36:04,2739704,NaN,0,2018-03-31
2739705,NON,sm-t550,Tablette,2018-03-31 21:47:18,Liens Sponsorisés,50634,1,les-nouveautes-du-printemps,2018-03-31 21:36:04,2739705,NaN,0,2018-03-31
2739706,NON,sm-t585,Tablette,2018-03-31 21:40:10,Moteurs,50709,1,les-nouveautes-du-printemps,2018-03-31 21:38:45,2739706,NaN,0,2018-03-31
2739707,NON,iPad,Tablette,2018-03-31 22:07:25,Accès Direct,51295,1,les-nouveautes-du-printemps,2018-03-31 22:05:10,2739707,NaN,0,2018-03-31
2739708,NON,NaN,Ordinateur,2018-03-31 22:07:31,Moteurs,51311,1,les-nouveautes-du-printemps,2018-03-31 22:06:16,2739708,NaN,0,2018-03-31
2739709,OUI,p023,Tablette,2018-03-31 22:10:00,Accès Direct,51333,1,les-nouveautes-du-printemps,2018-03-31 22:06:57,2739709,NaN,216442,2018-03-31
2739710,NON,NaN,Ordinateur,2018-03-31 22:18:36,Email marketing,51502,1,les-nouveautes-du-printemps,2018-03-31 22:14:16,2739710,NaN,0,2018-03-31
2739711,NON,NaN,Ordinateur,2018-03-31 22:19:41,Email marketing,51502,1,les-nouveautes-du-printemps,2018-03-31 22:14:16,2739711,NaN,0,2018-03-31
2739712,NON,iPad,Tablette,2018-03-31 22:47:20,Email marketing,52152,1,les-nouveautes-du-printemps,2018-03-31 22:43:32,2739712,NaN,0,2018-03-31
2739713,NON,NaN,Ordinateur,2018-03-31 22:57:25,Moteurs,52330,1,les-nouveautes-du-printemps,2018-03-31 22:51:22,2739713,NaN,0,2018-03-31
2739714,NON,NaN,Ordinateur,2018-03-31 22:52:50,Email marketing,52331,1,les-nouveautes-du-printemps,2018-03-31 22:51:37,2739714,NaN,0,2018-03-31
2739715,NON,iPad,Tablette,2018-03-31 23:22:37,Accès Direct,52916,1,les-nouveautes-du-printemps,2018-03-31 23:22:30,2739715,NaN,0,2018-03-31
2739716,NON,NaN,Ordinateur,2018-03-31 23:40:41,Accès Direct,53128,1,les-nouveautes-du-printemps,2018-03-31 23:35:17,2739716,NaN,0,2018-03-31
2739717,NON,NaN,Ordinateur,2018-03-31 23:45:24,Email marketing,53270,1,les-nouveautes-du-printemps,2018-03-31 23:45:18,2739717,NaN,0,2018-03-31
2739718,NON,NaN,Ordinateur,2018-03-31 23:56:12,Sites affluents,53326,1,les-nouveautes-du-printemps,2018-03-31 23:48:39,2739718,NaN,0,2018-03-31

In [16]:
logs_table.to_csv('logs.csv')

In [21]:
# Session ids are reset everyday. To count the number of visits over the 7 %morenths we observe, we compute the sum of the number of unique session_id per day
nb_of_id_sessions = pd.DataFrame(logs_table.groupby('SESSION_DATE').ID_SESSION.nunique())

In [80]:
nb_of_id_sessions.head()

              ID_SESSION
SESSION_DATE
2017-08-08         15092
2017-08-09         14749
2017-08-10         17449
2017-08-11         14171
2017-08-12         11081

In [23]:
total_visits = nb_of_id_sessions['ID_SESSION'].sum()
total_visits

7241180

## The total number of visits from 08-08-2017 to 31-03-2018 is 7 241 180.

In [ ]:
# Conversion rate = percentage of visitors who make an order

In [82]:
rate = total_nb_purchase/total_visits
rate

0.025958200182843127

# From 08-08-2017 to 31-03-2018, the conversion rate is about 2,6%.

In [37]:
logs['PAGES'].value_counts()

accueil                                                                                3275626
mon panier                                                                             1868520
header::moteur de recherche::page de resultat                                          1230200
ajout au panier                                                                        1123066
soldes                                                                                  911829
category 1::accueil category 1                                                          778907
accueil la chambre                                                                      725942
vente-privee                                                                            536490
mon compte ::accueil                                                                    449974
category 13::accueil category 13                                                        367249
category 1::category 1 fantaisie::accueil category 1 fantaisie                          364860
category 1::sous_category_-3503180197758226074::accueil -3503180197758226074            349474
ma livraison                                                                            332830
le-blanc                                                                                332211
identification::accueil                                                                 299674
evenement/jeu                                                                           297081
category 11::accueil category 11                                                        293108
category 3::accueil category 3                                                          278018
category 1::category 1 uni::accueil category 1 uni                                      258679
accueil la salle de bain                                                                245824
commander/recapitulatif.htm                                                             236520
accueil la table                                                                        234242
category 5::accueil category 5                                                          230741
automne-hiver                                                                           225381
mon paiement                                                                            210288
mes informations                                                                        205357
mon compte ::parametres de mon compte::suivre mes commandes                             187354
accueil les vetements d interieur                                                       181751
douceurs-d-hiver                                                                        179856
api.orangemail.orange.fr                                                                174438
                                                                                        ...
category 7::sous_category_5363949516691361235::fiche produit::2805992450799860187          317
category 5::category 5 fantaisies::fiche produit::8420557396930314173                      316
category 14::fiche produit::-6555887212575152042                                           316
category 3::category 3 fantaisie::fiche produit::1404199825328958966                       315
category 2::sous_category_6640754601682517410::fiche produit::8563751091274828193          313
category 1::sous_category_-3503180197758226074::fiche produit::-4022478202533366816        310
category 9::fiche produit::-4907039721824438423                                            309
category 2::sous_category_-400371345139020209::fiche produit::6087413366576324740          309
offre::offre::fiche produit::louise                                                        308
category 12::fiche produit::-4683847973722512718                                           297
category 1::sous_category_2653805293154512913::fiche produit::-8219645542541080832         296
offre::offre::fiche produit::torchon tranches d agrumes                                    293
category 20::sous_category_7544431040937753406::fiche produit::5065550042054032419         285
category 20::sous_category_7544431040937753406::accueil 7544431040937753406                281
category 28::fiche produit::-5201766006709156043                                           280
category 10::fiche produit::-4825325290148147421                                           274
category 4::fiche produit::-1918248336983187817                                            271
category 20::sous_category_55158009025041738::fiche produit::890007238030227243            271
category 26::fiche produit::3886049701521129723                                            271
category 20::sous_category_7544431040937753406::fiche produit::-5429518328117323799        270
category 9::fiche produit::3541400365135787315                                             269
category 20::category 9::fiche produit::8272354859893432574                                269
category 1::sous_category_-3503180197758226074::fiche produit::-6091802596981015466        262
category 24::fiche produit::-3411296731581998363                                           254
category 1::sous_category_-3503180197758226074::fiche produit::-1444238416816246137        253
category 10::fiche produit::-2880968927687489455                                           251
category 20::category 9::accueil category 9                                                247
category 20::sous_category_7544431040937753406::fiche produit::-4354326343212732148        245
category 1::category 1 uni::fiche produit::-3157328326782604108                            233
category 1::sous_category_-3503180197758226074::fiche produit::-7201803140063051326        232
Name: PAGES, Length: 1548, dtype: int64

In [91]:
panier = pd.DataFrame(logs_table[logs_table['PAGES'] == 'ajout au panier'])
panier

,CONNECTED_SESSION,DEVICE_MODEL,DEVICE_TYPE,EVENT_DATE,GLOBAL_SOURCES,ID_SESSION,LOADINGS,PAGES,SESSION_START_DATE,Unnamed: 0,Unnamed: 0.1,VISITOR_ID,SESSION_DATE
616487,OUI,NaN,Ordinateur,2017-08-08 00:04:14,Accès Direct,13,1,ajout au panier,2017-08-08 00:01:32,616487,NaN,563053,2017-08-08
616488,OUI,NaN,Ordinateur,2017-08-08 00:11:47,Accès Direct,13,1,ajout au panier,2017-08-08 00:01:32,616488,NaN,563053,2017-08-08
616489,OUI,NaN,Ordinateur,2017-08-08 00:13:37,Accès Direct,13,1,ajout au panier,2017-08-08 00:01:32,616489,NaN,563053,2017-08-08
616490,OUI,NaN,Ordinateur,2017-08-08 00:17:51,Accès Direct,13,1,ajout au panier,2017-08-08 00:01:32,616490,NaN,563053,2017-08-08
616491,OUI,NaN,Ordinateur,2017-08-08 00:01:29,Accès Direct,23,1,ajout au panier,2017-08-08 00:01:29,616491,NaN,706588,2017-08-08
616492,OUI,NaN,Ordinateur,2017-08-08 00:02:31,Accès Direct,23,1,ajout au panier,2017-08-08 00:01:29,616492,NaN,706588,2017-08-08
616493,OUI,NaN,Ordinateur,2017-08-08 00:10:17,Accès Direct,23,1,ajout au panier,2017-08-08 00:01:29,616493,NaN,706588,2017-08-08
616494,OUI,NaN,Ordinateur,2017-08-08 00:10:35,Accès Direct,23,1,ajout au panier,2017-08-08 00:01:29,616494,NaN,706588,2017-08-08
616495,OUI,NaN,Ordinateur,2017-08-08 00:24:22,Accès Direct,23,1,ajout au panier,2017-08-08 00:01:29,616495,NaN,706588,2017-08-08
616496,NON,iPad,Tablette,2017-08-08 00:06:40,Accès Direct,29,1,ajout au panier,2017-08-08 00:01:31,616496,NaN,0,2017-08-08
616497,NON,sm-g935f,Smartphone,2017-08-08 00:07:50,Accès Direct,34,1,ajout au panier,2017-08-08 00:01:32,616497,NaN,0,2017-08-08
616498,NON,sm-g935f,Smartphone,2017-08-08 00:11:30,Accès Direct,34,1,ajout au panier,2017-08-08 00:01:32,616498,NaN,0,2017-08-08
616499,NON,sm-g935f,Smartphone,2017-08-08 00:31:42,Accès Direct,34,1,ajout au panier,2017-08-08 00:01:32,616499,NaN,0,2017-08-08
616500,NON,sm-g920f,Smartphone,2017-08-08 00:05:43,Moteurs,83,1,ajout au panier,2017-08-08 00:05:10,616500,NaN,0,2017-08-08
616501,NON,sm-g920f,Smartphone,2017-08-08 00:06:12,Moteurs,83,1,ajout au panier,2017-08-08 00:05:10,616501,NaN,0,2017-08-08
616502,NON,sm-g920f,Smartphone,2017-08-08 00:07:18,Moteurs,83,1,ajout au panier,2017-08-08 00:05:10,616502,NaN,0,2017-08-08
616503,NON,NaN,Ordinateur,2017-08-08 00:12:14,Accès Direct,110,1,ajout au panier,2017-08-08 00:06:55,616503,NaN,0,2017-08-08
616504,NON,SM-T530,Tablette,2017-08-08 00:13:13,Accès Direct,129,1,ajout au panier,2017-08-08 00:08:25,616504,NaN,0,2017-08-08
616505,NON,NaN,Ordinateur,2017-08-08 00:29:26,Accès Direct,131,1,ajout au panier,2017-08-08 00:08:42,616505,NaN,0,2017-08-08
616506,NON,NaN,Ordinateur,2017-08-08 00:30:12,Accès Direct,131,1,ajout au panier,2017-08-08 00:08:42,616506,NaN,0,2017-08-08
616507,NON,NaN,Ordinateur,2017-08-08 00:32:59,Accès Direct,131,1,ajout au panier,2017-08-08 00:08:42,616507,NaN,0,2017-08-08
616508,NON,NaN,Ordinateur,2017-08-08 00:33:42,Accès Direct,131,1,ajout au panier,2017-08-08 00:08:42,616508,NaN,0,2017-08-08
616509,NON,NaN,Ordinateur,2017-08-08 00:36:18,Accès Direct,131,1,ajout au panier,2017-08-08 00:08:42,616509,NaN,0,2017-08-08
616510,NON,NaN,Ordinateur,2017-08-08 00:13:36,Accès Direct,142,1,ajout au panier,2017-08-08 00:09:09,616510,NaN,0,2017-08-08
616511,NON,NaN,Ordinateur,2017-08-08 00:20:09,Accès Direct,142,1,ajout au panier,2017-08-08 00:09:09,616511,NaN,0,2017-08-08
616512,NON,NaN,Ordinateur,2017-08-08 00:33:27,Sources naturelles personnalisées,206,1,ajout au panier,2017-08-08 00:15:07,616512,NaN,0,2017-08-08
616513,NON,sm-j510fn,Smartphone,2017-08-08 00:27:59,Email marketing,224,1,ajout au panier,2017-08-08 00:17:09,616513,NaN,0,2017-08-08
616514,NON,sm-j510fn,Smartphone,2017-08-08 00:32:25,Email marketing,224,1,ajout au panier,2017-08-08 00:17:09,616514,NaN,0,2017-08-08
616515,NON,NaN,Ordinateur,2017-08-08 00:24:39,Liens Sponsorisés,236,1,ajout au panier,2017-08-08 00:17:52,616515,NaN,0,2017-08-08
616516,NON,NaN,Ordinateur,2017-08-08 00:26:41,Liens Sponsorisés,236,1,ajout au panier,2017-08-08 00:17:52,616516,NaN,0,2017-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581833,NON,iPad,Tablette,2018-03-31 23:17:14,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581833,NaN,0,2018-03-31
581834,NON,iPad,Tablette,2018-03-31 23:17:37,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581834,NaN,0,2018-03-31
581835,NON,iPad,Tablette,2018-03-31 23:19:43,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581835,NaN,0,2018-03-31
581836,NON,iPad,Tablette,2018-03-31 23:21:44,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581836,NaN,0,2018-03-31
581837,NON,iPad,Tablette,2018-03-31 23:23:50,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581837,NaN,0,2018-03-31
581838,NON,iPad,Tablette,2018-03-31 23:37:49,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581838,NaN,0,2018-03-31
581839,NON,iPad,Tablette,2018-03-31 23:38:58,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581839,NaN,0,2018-03-31
581840,NON,iPad,Tablette,2018-03-31 23:42:00,Moteurs,52802,1,ajout au panier,2018-03-31 23:16:34,581840,NaN,0,2018-03-31
581841,OUI,NaN,Ordinateur,2018-03-31 23:20:12,Liens Sponsorisés,52816,1,ajout au panier,2018-03-31 23:17:19,581841,NaN,615922,2018-03-31
581842,OUI,NaN,Ordinateur,2018-03-31 23:21:22,Liens Sponsorisés,52816,1,ajout au panier,2018-03-31 23:17:19,581842,NaN,615922,2018-03-31
581843,OUI,sm-g920f,Smartphone,2018-03-31 23:35:48,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581843,NaN,457841,2018-03-31
581844,OUI,sm-g920f,Smartphone,2018-03-31 23:36:27,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581844,NaN,457841,2018-03-31
581845,OUI,sm-g920f,Smartphone,2018-03-31 23:40:50,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581845,NaN,457841,2018-03-31
581846,OUI,sm-g920f,Smartphone,2018-03-31 23:43:46,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581846,NaN,457841,2018-03-31
581847,OUI,sm-g920f,Smartphone,2018-03-31 23:44:15,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581847,NaN,457841,2018-03-31
581848,OUI,sm-g920f,Smartphone,2018-03-31 23:44:37,Liens Sponsorisés,52853,1,ajout au panier,2018-03-31 23:19:09,581848,NaN,457841,2018-03-31
581849,NON,NaN,Ordinateur,2018-03-31 23:23:02,Publicité,52919,1,ajout au panier,2018-03-31 23:22:38,581849,NaN,0,2018-03-31
581850,NON,sm-t550,Tablette,2018-03-31 23:39:33,Moteurs,53033,1,ajout au panier,2018-03-31 23:29:24,581850,NaN,0,2018-03-31
581851,NON,NaN,Ordinateur,2018-03-31 23:36:25,Liens Sponsorisés,53067,1,ajout au panier,2018-03-31 23:31:59,581851,NaN,0,2018-03-31
581852,NON,NaN,Ordinateur,2018-03-31 23:40:16,Liens Sponsorisés,53067,1,ajout au panier,2018-03-31 23:31:59,581852,NaN,0,2018-03-31
581853,NON,NaN,Ordinateur,2018-03-31 23:42:13,Liens Sponsorisés,53067,1,ajout au panier,2018-03-31 23:31:59,581853,NaN,0,2018-03-31
581854,NON,SM-T520,Tablette,2018-03-31 23:41:08,Liens Sponsorisés,53158,1,ajout au panier,2018-03-31 23:37:05,581854,NaN,0,2018-03-31
581855,NON,SM-T520,Tablette,2018-03-31 23:42:30,Liens Sponsorisés,53158,1,ajout au panier,2018-03-31 23:37:05,581855,NaN,0,2018-03-31
581856,NON,SM-T520,Tablette,2018-03-31 23:54:44,Liens Sponsorisés,53158,1,ajout au panier,2018-03-31 23:37:05,581856,NaN,0,2018-03-31
581857,NON,NaN,Ordinateur,2018-03-31 23:40:20,Email marketing,53171,1,ajout au panier,2018-03-31 23:38:26,581857,NaN,0,2018-03-31
581858,OUI,iPhone,Smartphone,2018-03-31 23:51:08,Liens Sponsorisés,53205,1,ajout au panier,2018-03-31 23:40:24,581858,NaN,763776,2018-03-31
581859,OUI,iPhone,Smartphone,2018-03-31 23:51:33,Liens Sponsorisés,53205,1,ajout au panier,2018-03-31 23:40:24,581859,NaN,763776,2018-03-31
581860,OUI,iPad,Tablette,2018-03-31 23:56:44,Email marketing,53382,1,ajout au panier,2018-03-31 23:53:15,581860,NaN,803843,2018-03-31
581861,OUI,iPad,Tablette,2018-03-31 23:57:09,Email marketing,53382,1,ajout au panier,2018-03-31 23:53:15,581861,NaN,803843,2018-03-31
581862,NON,iPhone,Smartphone,2018-03-31 23:58:14,Email marketing,53416,1,ajout au panier,2018-03-31 23:56:34,581862,NaN,0,2018-03-31

In [90]:
len(panier)

1123066

In [97]:
# Computing the number of people (unique session_id) who put items in their cart per day

panier_per_day = pd.DataFrame(panier.groupby('SESSION_DATE').ID_SESSION.nunique())
panier_per_day.head()

              ID_SESSION
SESSION_DATE
2017-08-08          1847
2017-08-09          1089
2017-08-10           956
2017-08-11           886
2017-08-12           734

In [95]:
total_panier = panier_per_day['ID_SESSION'].sum()
total_panier

431245

CART CONVERSION RATE

In [99]:
cart_conversion = total_nb_purchase/total_panier
cart_conversion

0.4358728796855616

FROM VISIT TO CART

In [100]:
add_to_cart = total_panier/total_visits
add_to_cart

0.059554520119649006

In [101]:
add_to_cart * cart_conversion

0.02595820018284313

In [102]:
rate

0.025958200182843127

# CONVERSION TABLE

In [84]:
conversion = pd.read_csv('Data/TABLE_CONVERSION.csv', delimiter=';')
conversion.head()

   Unnamed: 0  VISITOR_ID        CLIENT_NUMBER
0           0      153926  2117916268519517296
1           1      153987 -3983308646720649306
2           2      153992 -2525192206264180159
3           3      153996  1543724696132514059
4           4      154002 -3753347333864614269

# MERGING THE TABLES

In [ ]:
nb_orders_data = pd.DataFrame(orders.groupby(by=‘CLIENT_NUMBER’)[‘ORDER_NUMBER’].count())

clust_data = pd.merge(clust_data, nb_orders_data, how=‘left’, left_index=True, right_index=True)
clust_data = clients[[‘CLIENT_NUMBER’, ‘CREATION_DATE’, ‘GENDER’]].copy()
clust_data.dropna(inplace=True)
clust_data.set_index(‘CLIENT_NUMBER’, inplace=True)